package RLarkin_Project_1;

// CMSC 330 Advanced Programming Languages
// Project 1 Skeleton
// UMGC CITE
// August 2021

// Enumerated type that defines the list of tokens
// Added tokens: ISOSCELES, PARALLELOGRAM, REGULAR_POLYGON, TEXT, SIDES, RADIUS, OFFSET

enum Token {AT, COLOR, END,	HEIGHT, RECTANGLE, RIGHT_TRIANGLE, ISOSCELES, PARALLELOGRAM, 
	REGULAR_POLYGON, SCENE, WIDTH, COMMA, SEMICOLON, PERIOD, LEFT_PAREN, RIGHT_PAREN, IDENTIFIER, NUMBER, 
	EOF, OFFSET, TEXT, SIDES, RADIUS}